# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
#  - exercise
  - test

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules

# Jobs   

install_dependencies:
  stage: install
  only:
    - develop
  script:
    - npm ci

bundle_app:
  stage: build
  only:
    - develop
  script:
    - npm run build
  artifacts:
    paths:
      - build/

# tests

e2etest:    
  stage: test
  only:
    - staging
    - master
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
      # start the server in the background
    - npm run start:ci



# build_jobX:
#   stage: build
#   only:
#     - demobranch
#   script:
#     - echo "build job X on demoBranch works"

# exercise_job:
#   stage: exercise
#   only:
#     - master
#   script:
#     - echo "exercise job X"

# test_jobX:
#   stage: test
#   only:
#     - master
#     - demobranch2
#   script:
#     - echo "test job X"